services:

  postgres:
    image: postgres:16
    container_name: ti-batch-postgres
    environment:
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --auth-local=scram-sha-256
      POSTGRES_USER: ti_dbuser
      POSTGRES_PASSWORD: tiuser!23456
      POSTGRES_DB: tinitiateai
    ports:
      - "5432:5432"
    volumes:
      - ti_pyspark_postgres_data:/var/lib/postgresql/data
      - ./sql:/lab/sql:ro
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro

  minio:
    image: minio/minio
    container_name: ti-batch-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  spark-master:
    image: bde2020/spark-master:latest
    container_name: ti-batch-spark-master
    environment:
      INIT_DAEMON_STEP: setup_spark
    ports:
      - "7077:7077"
      - "8088:8080"

  spark-worker:
    image: bde2020/spark-worker:latest
    container_name: ti-batch-spark-worker
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
    ports:
      - "8089:8081"

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: ti-batch-jupyter
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    volumes:
      - ../:/home/jovyan/work
    environment:
      SPARK_MASTER: spark://spark-master:7077
      JUPYTER_TOKEN: admin123

volumes:
  ti_pyspark_postgres_data:
  minio_data:
